/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tp.pp2.rpg.generator.gui;

public class App {
    public String getGreeting() {
        return "Hello World! Main";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
